# Generated by Django 5.1.3 on 2024-12-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_garden_user_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='days_until_mature',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
