# Generated by Django 5.1.4 on 2024-12-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_plant_daysuntilmature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='days_since_watered',
            field=models.IntegerField(default=0),
        ),
    ]
