# Generated by Django 5.1.4 on 2024-12-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_plot_days_since_watered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='days_since_planted',
            field=models.IntegerField(db_column='days_since_planted', default=0),
        ),
        migrations.AlterField(
            model_name='plant',
            name='days_until_mature',
            field=models.IntegerField(db_column='days_until_mature'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='days_since_watered',
            field=models.IntegerField(db_column='daysincewatered', default=0),
        ),
    ]
